### ISSUE TITLE
[NEW FEATURE] Define verbose mode for warnings

### ISSUE THREAD

**Issue by tobias-liaudat** [CEA-COSMIC/ModOpt#100]
**Is your feature request related to a problem? Please describe.**
This is requested to solve this : [issue](https://github.com/CosmoStat/mccd/issues/2) on the MCCD package.

In summary, the MCCD algorithms uses some optimization algorithms form the ModOpt package. For that the gradient class `GradParent()` is used from `.opt.gradient.py` and the function `check_npndarray()` from `.base.types.py` throws the warning 'Making input data immutable.' for each instance of the gradient class I have when I run the algorithm.

The main issue is that when the MCCD algorithm is run over a big amount of data, it outputs some big stdout files that are unwanted. 

**Describe the solution you'd like**
It could be possible to add a verbose attribute to the `GradParent()` class that would be passed to  `check_npndarray()` in order to control its behaviour. As the function `check_npndarray()` has a verbose variable but it is defaulted to True always in that case.

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

If @sfarrens you're ok with it I can propose a pull request for this.

**Comment by sfarrens** [comment]
@tobias-liaudat I agree with what you have proposed. You ticked that you are planning a PR for this. If so, I will wait to check it, if not let me know and I will open a PR.
