### ISSUE TITLE
New release 1.5 broke some downstream code

### ISSUE THREAD

**Issue by tomMoral** [CEA-COSMIC/ModOpt#144]
Hello,

Thanks for this nice optimization package. We are developing a framework for automatic benchmarking of optimization libraries called [`benchopt`](https://benchopt.github.io) where we included [`modopt` for the lasso](https://github.com/benchopt/benchmark_lasso/pull/7) (with the help of @zaccharieramzi ). I just wanted to report here that the latest release `1.5` broke our down stream code for two reasons:

- The API changed without deprecation warning cycle. When `1.5` was released, `data` changed in a lot of places to `input_data`. software development best practices would have been to support both `data` and `input_data` for at least one release, with deprecation warning to make sure downstream code can be updated without breaking it. It is not a very big deal but at least mentionning the change in the what's new would be nice.

- We also realized that the requirements impose pinned  version of the dependencies like `numpy`. This tends to break compat with many other packages installed in a distribution and should be avoided if possible. At least using something like `1.19` would already help a lot instead of even pinning the release number. It would be nice to remove the pinned version from the requirement file.

I think fixing this and making sure to keep a stable API would make the package more robust for users. hope this can help for future development! :)

**Comment by sfarrens** [comment]
Hi @tomMoral, thanks for the feedback it is very much appreciated.

- The API issue is 100% my fault and fell through the cracks as I rushed to get the last release finished on time, so sorry about that.
- The pinned dependencies was deliberate as we were aiming to keep all of PySAP consistent and still maintain support for Python 3.6. I will take another look at this and see if I can keep everything stable with minimum rather than fixed package versions. If so, I can release a patch for this.

**Comment by agramfort** [comment]
@sfarrens what is common practice is to have CIs that run both the minimal dependencies and the current stable. Pinning dependencies will lead to situations where 2 software are simply incompatible in the same environment.

**Comment by sfarrens** [comment]
> @sfarrens what is common practice is to have CIs that run both the minimal dependencies and the current stable. Pinning dependencies will lead to situations where 2 software are simply incompatible in the same environment.

I will look into this, thanks @agramfort!

**Comment by sfarrens** [comment]
Pinned dependencies removed in #189

**Comment by tomMoral** [comment]
:pray: nice, we will be able to update our benchmarks to include back `ModOpt`.
Thanks!
