### ISSUE TITLE
Low rank constraint with highly rectangular matrix

### ISSUE THREAD

**Issue by SylvainLan** [CEA-COSMIC/ModOpt#20]
Hello, 

I would like to solve a low rank relaxed problem of the kind : 

`||Ex-y||^2 + ||x||_*`

Where my data x is of shape (N,M) where N is typically 128*128 and M 32. 

When I'm using the LowRankMatrix proximity in ModOpt I get a MemoryError because scipy tries to calculate the full svd and therefore wants to build a 128^^4 matrix, which I can't store. 

I was wondering if I could change the way to calculate the svd by using the `full_matrices` argument from scipy. 

I'm making a PR to open the discussion.

**Comment by sfarrens** [comment]
Issue closed following merge of PR #21
