### ISSUE TITLE
Implement the POGM algorithm

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/ModOpt#38]
The [POGM algorithm](https://link.springer.com/article/10.1007/s10957-018-1287-4) has been found to be the best algorithm to apply to a synthesis formulation of the MRI reconstruction problem in a [recent benchmark](https://arxiv.org/pdf/1903.03510.pdf).

Having it as one of the algorithm in our repo could be very useful for benchmarking.

**Comment by sfarrens** [comment]
Resolved in #41
