### ISSUE TITLE
Typo in Condat docs

### ISSUE THREAD

**Issue by zaccharieramzi** [CEA-COSMIC/ModOpt#44]
There is a typo in the docs of the Condat-Vu algorithm. [When referencing the paper](https://github.com/CEA-COSMIC/ModOpt/blob/master/modopt/opt/algorithms.py#L867), it says that it implements the algorithm 10.7. But there is no such algorithm [in the paper](https://www.gipsa-lab.grenoble-inp.fr/~laurent.condat/publis/Condat-optim-JOTA-2013.pdf). My guess it it's because the [forward backward implements the algorithm 10.7](https://github.com/CEA-COSMIC/ModOpt/blob/master/modopt/opt/algorithms.py#L568) of another paper, and so the typo comes from there.

It actually implements 3.1, [which is referenced afterwards in another doc](https://github.com/CEA-COSMIC/ModOpt/blob/master/modopt/opt/algorithms.py#L986).

**Comment by sfarrens** [comment]
Resolved in #47
