### ISSUE TITLE
Make progressbar optional in optim algorithms

### ISSUE THREAD

**Issue by MorganSchmitz** [CEA-COSMIC/ModOpt#46]
so you can run them 100% quietly

**Comment by zaccharieramzi** [comment]
Are you taking care of it? I would also benefit from it, so I can do it if you don't.

**Comment by sfarrens** [comment]
@zaccharieramzi I was planning to resolve this next week, before the SILICOSMIC meeting, but you are welcome to submit a PR for this before then if you want.

**Comment by sfarrens** [comment]
Resolved in #47, simply pass argument `progress=False` to any algorithm.
