### ISSUE TITLE
Implementing the Ordered Weighted l1-norm proximity operator

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/ModOpt#48]
It would be great to have the [Ordered Weighted L1-norm](https://arxiv.org/pdf/1409.4271.pdf) proximity operator implemented in ModOpt. This norm is known to have good statistical properties as a sparsity promoting regularizer and also to be the generalization of the [Octagonal Shrinkage and Clustering Algorithm for Regression](https://pdfs.semanticscholar.org/2655/31298885e589ad6613173b5c5cb08cf78644.pdf)
which overcomes one of the biggest weakness of the LASSO regularization: when variables became highly correlated. 

**Solution**
The solution would be to implement the `Eq. (24)` in the [OWL](https://arxiv.org/pdf/1409.4271.pdf) paper. Moreover the proximity operator could be unit-tested using it relation with the LASSO.

**Comment by sfarrens** [comment]
Resolved in #52
