### ISSUE TITLE
[BUG] Progressbar parameter max_value -> maxval

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/ModOpt#59]
`if self.progress:
            with ProgressBar(redirect_stdout=True, max_value=max_iter) as bar:
                self._iterations(max_iter, bar=bar)
        else:
            self._iterations(max_iter)
`
I see that in progressbar it is maxval and not max_value , This is with python3.5 and progressbar version 2.5 .. Is this just version mismatch, as I already had things working fine on python3.6

**Comment by zaccharieramzi** [comment]
I think it's because we are using `progressbar-2` and not `progressbar` (different package not version). See [these examples](https://progressbar-2.readthedocs.io/en/latest/examples.html) where they use `max_value`.

**Comment by chaithyagr** [comment]
Ahh, as I pointed it is just a matter of version miss-match.. Given we are clear on what we are using, I dont there is anything that needs to be done here.. Thanks @zaccharieramzi . I will close this issue here, sorry for the unwanted bother..
