### ISSUE TITLE
[NEW FEATURE]: K-support norm proximity operator implementation

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/ModOpt#68]
**Is your feature request related to a problem? Please describe.**
For multi-task learning or calibrationless method the k-support norm is a great structured sparsity norm

**Describe the solution you'd like**
The solution has originally been proposed by [McDonald](http://jmlr.org/papers/volume17/15-151/15-151.pdf) and the idea would be to implement Algorithm 1 page 18 in the special case of k-support norm

**Describe alternatives you've considered**
An alternative idea would be to implement the method proposed by [Argyriou](https://papers.nips.cc/paper/4537-sparse-prediction-with-the-k-support-norm.pdf)

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
Resolved in #71
