### ISSUE TITLE
[NEW FEATURE]: Ridge et Elastic Net as regularization

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/ModOpt#69]
**Is your feature request related to a problem? Please describe.**
Ridge & Elastic-net are considered as traditional regularization for predictions, It also enables other applications such as parallel MRI reconstruction

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
resolved in #70
