### ISSUE TITLE
[BUG]: skimage.metrics only exists for python version > 3.6

### ISSUE THREAD

**Issue by LElgueddari** [CEA-COSMIC/ModOpt#72]
**System setup**
Python version: [e.g.] v3.5

**Describe the bug**
scikit-image dropped the support of python 3.5, making  SSIM unusable in python 3.5 even if scikit-image has been installed. 

**Module and lines involved**
for more information see scikit-image  [release note](https://github.com/scikit-image/scikit-image/blob/master/doc/release/release_0.16.rst) that is involved in [ssim](https://github.com/CEA-COSMIC/ModOpt/blob/07ed9c31b0623e11fe122eac5d38d2ceb7e74214/modopt/math/metrics.py#L14)

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
Resolved in #73
