### ISSUE TITLE
[QoL] Consistent naming scheme for step size parameters in FB/GFB

### ISSUE THREAD

**Issue by MorganSchmitz** [CEA-COSMIC/ModOpt#75]
**Is your feature request related to a problem? Please describe.**
The main step size parameter is called `beta_param`  in FB but `gamma_param` in GFB. I know these are so they exactly match the papers cited, but I think it might be easier on the user if they had the same name?

**Describe the solution you'd like**
Maybe forego letters completely and just call them `step_size`...?

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No

**Comment by sfarrens** [comment]
@MorganSchmitz I think it would be pretty easy to add a generic `step_size` parameter to the parent class of the algorithms, which could be used to set the algorithm specific parameter values.

I will open a PR for this.
