### ISSUE TITLE
[NEW FEATURE] Call Metrics after last iteration

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/ModOpt#84]
Currently the mterics are called only after metric call period.

I would like to implement 2 things:
1) A Way to keep metric call period infinite, ie we dont call to metrics at all.
2) An option to call metric always at the end of iterations. 

These 2 above features help a lot, especially in a grid search. We can obtain the values at say the beginning and end of iterations or maybe only at the end of iterations

**Are you planning to submit a Pull Request?**
- [X] Yes, after getting your views on this @zaccharieramzi @sfarrens 
- [ ] No

**Comment by zaccharieramzi** [comment]
Sounds good
