### ISSUE TITLE
[BUG] Update ` get_notify_observers_kwargs` for POGM to return atleast one image space variable

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/ModOpt#85]
**Describe the bug**

Currently, POGM holds wavelet coefficients in all cases.
This causes issues in trying to define `ssim` and other related metrics that need input as an image.
Although this seems more of an enhancement issue, I am marking it as a bug as this breaks the functionality of metrics with POGM.

https://github.com/CEA-COSMIC/ModOpt/blob/609ecded944b6bfd746106c917d6043219701fa4/modopt/opt/algorithms.py#L1237-L1246

This will mostly be a short PR and @sfarrens can we please wait for this PR before a release?

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
@chaithyagr no problem, I will wait for the PR. 😃
