### ISSUE TITLE
[NEW FEATURE] Add supoort to ensure we never calculate cost

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/ModOpt#87]
Currently, we calculate cost at every N iterations through :
call:

https://github.com/CEA-COSMIC/ModOpt/blob/609ecded944b6bfd746106c917d6043219701fa4/modopt/opt/algorithms.py#L598-L600

actual per N:
https://github.com/CEA-COSMIC/ModOpt/blob/609ecded944b6bfd746106c917d6043219701fa4/modopt/opt/cost.py#L185-L190

However, there is no way to ensure that we never calculate cost function at all. 
I propose:
1) Have extra line that checks if `cost_interval` is `None`, in which case we return without cost calculation.
2) By default make `cost_interval` to None ie never calculate, rather than calculate at every iteration. In my opinion, we will gain a speedup of nearly 2 if we do this by default and allow user to specify only if he uses cost value.
 

**Are you planning to submit a Pull Request?**
- [X] Yes, @zaccharieramzi  and @sfarrens can you please sign off on my proposals so that I can get this as a PR?
Also, @sfarrens as it is a minor 2-3 line PR, we can have this too in release (I know I am having a lot at this point of time, but I just find the impact quite high)
- [ ] No

**Comment by sfarrens** [comment]
@chaithyagr I think it is a really good idea to allow a `None` value for the cost interval. I am not as convinced it should be the default. It seems to be that the default should be the "safest" (by that I mean the user can trust the results as much as possible) rather than the fastest. I think a measure of the cost is pretty essential for the initial analysis, afterwards a faster approach can be adopted.

**Comment by chaithyagr** [comment]
Sure, I had this doubt, thanks for confirmation. 
However, in pysap-mri, I will make it None as default for us as seldom do we use the cost values, we are more concerned on the metrics (which has little or no overhead)
However, I understand that as Modopt is actual optimization toolbox, by default, it must calculate costs

**Comment by sfarrens** [comment]
@chaithyagr Sounds good. Within the context of a plugin tool I think it is fine to make the default `None`.
